Resources:
  S3deliverystream:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: voga-firehose-events-deliverystreams
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

# this
      