name: Event_Recoder

on:
  push:
    branches:
      - main

jobs:
  Build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: SAM Build
        run: sam build
      - name: Download dependencies
        run:  pip install -r requirements.txt -t .aws-sam/build/collector-dependencies/python/
      - name: SAM Deploy - AWS
        run: sam deploy --template-file template.yaml --stack-name events-streams-v5 --capabilities CAPABILITY_IAM --s3-bucket vogasamclick --region eu-west-1

      # - name: Deploy to AWS
      #   run: |
      #     sam build
      #     pip install -r requirements.txt -t .aws-sam/build/collector-dependencies/python/
      #     ls -a
      #     sam deploy --template-file template.yaml --stack-name events-streams-v5 --capabilities CAPABILITY_IAM --s3-bucket vogasamclick --region eu-west-1